# Generated by Django 4.0.4 on 2022-05-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_rename_contactform_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='comment',
            field=models.TextField(blank=True, help_text='Your Message', null=True),
        ),
    ]
