# Generated by Django 4.0.4 on 2022-05-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_eventmodel_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='title',
            new_name='title_name',
        ),
    ]
