# Generated by Django 4.0.4 on 2022-05-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_remove_commentmodel_tags_blogmodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='name',
            field=models.CharField(default=1, help_text='Phone Number', max_length=10),
            preserve_default=False,
        ),
    ]
