# Generated by Django 4.0.4 on 2022-05-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_alter_volunteermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteermodel',
            name='fb_url',
            field=models.CharField(blank=True, help_text='Facebook Link Page', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='volunteermodel',
            name='ig_url',
            field=models.CharField(blank=True, help_text='Instagram Link Page', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='volunteermodel',
            name='li_url',
            field=models.CharField(blank=True, help_text='Linkedin Link Page', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='volunteermodel',
            name='tw_url',
            field=models.CharField(blank=True, help_text='Twitter Link Page', max_length=300, null=True),
        ),
    ]
