# Generated by Django 4.0.4 on 2022-05-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_volunteermodel_fb_url_volunteermodel_ig_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('campaign_hashlink', models.CharField(help_text='Hashlink of featured campaign e.g. Life, Food, Education etc.', max_length=50)),
                ('campaign_heading', models.CharField(help_text='Heading of featured campaign', max_length=100)),
                ('campaign_description', models.CharField(help_text='Description of featured campaign', max_length=100)),
                ('campaign_donation_goal', models.PositiveIntegerField(default=1)),
                ('campaign_donation_raised', models.PositiveIntegerField(default=1)),
                ('campaign_donation_to_go', models.PositiveIntegerField(default=1)),
                ('campaign_bar_data', models.PositiveIntegerField(default=1, help_text='Maximum bar size 100')),
                ('image', models.ImageField(help_text='resolution of 552x310', upload_to='campaign_image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
