# Generated by Django 4.0.4 on 2022-05-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_eventmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='photo',
            field=models.TextField(null=True),
        ),
    ]
