# Generated by Django 4.0.4 on 2022-05-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_eventmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='description',
            field=models.TextField(blank=True, help_text='Description', null=True),
        ),
    ]
