# Generated by Django 4.0.4 on 2022-05-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_alter_eventmodel_photo'),
        ('models', '0010_eventmodel_event_banner_pagephoto_and_more'),
    ]

    operations = [
    ]
