# Generated by Django 4.0.4 on 2022-05-15 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_commentmodel_blogmodel_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='comments',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.blogmodel'),
        ),
    ]
