# Generated by Django 4.0.4 on 2022-05-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_remove_blogmodel_comments_commentmodel_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma Separated Tag', max_length=200, null=True),
        ),
    ]
