# Generated by Django 4.0.4 on 2022-05-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_rename_date_contactform_modified_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetHelpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(help_text='First Name', max_length=50)),
                ('last_name', models.CharField(help_text='Last Name', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Email', max_length=70, null=True)),
                ('phone', models.CharField(help_text='Phone Number', max_length=10)),
                ('get_help_for', models.CharField(choices=[('RHC', 'Rehabilitation'), ('DDA', 'Drug De Addiction'), ('SDDA', 'Smoking De Addiction'), ('ADA', 'Alcohol De-Addiction'), ('MC', 'Mental Counselling'), ('OLH', 'Old Aged Home'), ('CS', 'Childcare Support'), ('OTH', 'Others')], default='RHC', max_length=100)),
                ('address', models.TextField(blank=True, help_text='Address', null=True)),
                ('country', models.CharField(choices=[('IN', 'India'), ('OTH', 'Others')], default='IN', max_length=50)),
                ('state', models.CharField(choices=[('AN', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CH', 'Chandigarh'), ('CT', 'Chhattisgarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('LD', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PY', 'Puducherry'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UT', 'Uttarakhand'), ('WB', 'West Bengal'), ('OTH', 'Others')], default='MH', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerMoodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(help_text='First Name', max_length=50)),
                ('last_name', models.CharField(help_text='Last Name', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Email', max_length=70, null=True)),
                ('phone', models.CharField(help_text='Phone Number', max_length=10)),
                ('volunteering_for', models.CharField(choices=[('BLC', 'Blood Donation Camp'), ('RHC', 'Rehabilation Camp'), ('CRC', 'Child Related Camp'), ('OTH', 'Others Activities'), ('ALL', 'ALL')], default='ALL', max_length=100)),
                ('address', models.TextField(blank=True, help_text='Address', null=True)),
                ('country', models.CharField(choices=[('IN', 'India'), ('OTH', 'Others')], default='IN', max_length=50)),
                ('state', models.CharField(choices=[('AN', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CH', 'Chandigarh'), ('CT', 'Chhattisgarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('LD', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PY', 'Puducherry'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UT', 'Uttarakhand'), ('WB', 'West Bengal'), ('OTH', 'Others')], default='MH', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='name',
        ),
        migrations.AddField(
            model_name='contactform',
            name='first_name',
            field=models.CharField(default='aa', help_text='First Name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactform',
            name='last_name',
            field=models.CharField(default='aa', help_text='Last Name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactform',
            name='comments',
            field=models.CharField(blank=True, help_text='Phone Number', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(blank=True, help_text='Email', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='phone',
            field=models.CharField(help_text='Phone Number', max_length=10),
        ),
    ]
