# Generated by Django 4.0.4 on 2022-05-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main_project_image'),
        ),
    ]
