# Generated by Django 4.0.4 on 2022-05-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_featuredcampaigns_feature_bar_data_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeaturedCampaigns',
            new_name='FeaturedCampaign',
        ),
    ]
