# Generated by Django 4.0.4 on 2022-05-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_volunteermodel_delete_volunteermoodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteermodel',
            name='image',
            field=models.ImageField(blank=True, help_text='resolution of 400x225', null=True, upload_to='volunteers_image'),
        ),
        migrations.AlterField(
            model_name='featuredcampaign',
            name='image',
            field=models.ImageField(help_text='resolution of 400x225', upload_to='featured_campaign_image'),
        ),
    ]
