# Generated by Django 4.0.4 on 2022-05-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_volunteermodel_image_alter_featuredcampaign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteermodel',
            name='email',
            field=models.EmailField(help_text='Email', max_length=70),
        ),
        migrations.AlterField(
            model_name='volunteermodel',
            name='full_name',
            field=models.CharField(help_text='Full Name', max_length=70),
        ),
    ]
